parameters:
    urbanara.driver.order.class: UrbanaraBundle\Driver\OrderDriver

    urbanara.client.dummy.class: UrbanaraBundle\Client\DummyClient
    urbanara.client.sylius.class: UrbanaraBundle\Client\SyliusClient

    urbanara.shop_connector.class: UrbanaraBundle\Connector\ShopConnector

    urbanara.checker.order_statuses.class: UrbanaraBundle\Checker\OrdersStatusesChecker
services:
    urbanara.registry.order_client:
        class: %sylius.registry.promotion_action.class%
        arguments:
            - "UrbanaraBundle\\Client\\OrderClientInterface"
            - "order client"

    urbanara.driver.order:
        class: %urbanara.driver.order.class%
        arguments: [@urbanara.registry.order_client]

    urbanara.client.dummy:
        class: %urbanara.client.dummy.class%
        tags:
            - { name: "urbanara.client", type: "dummy" }
    urbanara.client.sylius:
        class: %urbanara.client.sylius.class%
        arguments: [@sylius.repository.order]
        tags:
            - { name: "urbanara.client", type: "sylius" }

    urbanara.shop_connector:
        class: %urbanara.shop_connector.class%
        arguments: [@urbanara.driver.order, @urbanara.checker.order_statuses]

    urbanara.checker.order_statuses:
        class: %urbanara.checker.order_statuses.class%
        arguments: [@urbanara.driver.order]
