parameters:
    urbanara.driver.dummy.class: UrbanaraBundle\Driver\DummyClientDriver
    urbanara.driver.sylius.class: UrbanaraBundle\Driver\SyliusClientDriver

    urbanara.client.dummy.class: UrbanaraBundle\Client\DummyClient
    urbanara.client.sylius.class: UrbanaraBundle\Client\SyliusClient

    urbanara.shop_connector.class: UrbanaraBundle\Connector\ShopConnector

    urbanara.checker.order_statuses.class: UrbanaraBundle\Checker\OrdersStatusesChecker

    urbanara.registry.order_driver.class: Sylius\Component\Registry\ServiceRegistry
services:
    urbanara.registry.order_driver:
        class: %urbanara.registry.order_driver.class%
        arguments:
            - "UrbanaraBundle\\Driver\\OrderDriverInterface"
            - "order driver"

    urbanara.driver.dummy:
        class: %urbanara.driver.dummy.class%
        arguments: [@urbanara.client.dummy]
        tags:
            - { name: "urbanara.order_driver", client: "dummy" }
    urbanara.sylius.dummy:
        class: %urbanara.driver.sylius.class%
        arguments: [@urbanara.client.sylius]
        tags:
            - { name: "urbanara.order_driver", client: "sylius" }

    urbanara.client.dummy:
        class: %urbanara.client.dummy.class%
    urbanara.client.sylius:
        class: %urbanara.client.sylius.class%
        arguments: [@sylius.repository.order]

    urbanara.shop_connector:
        class: %urbanara.shop_connector.class%
        arguments: [@urbanara.checker.order_statuses]

    urbanara.checker.order_statuses:
        class: %urbanara.checker.order_statuses.class%
        arguments: [@urbanara.registry.order_driver]
